import Head from 'next/head'
import { Preloader } from "../modules/Preloader/Preloader";
import { Home } from "../modules/Home/Home";
import { Spring } from "../modules/Spring/Spring";
import { Order } from "../modules/Order/Order";

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>Brioni Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Preloader /> */}
      <Home />
      <Spring />
      <Order />
    </div>
  );
}