const dbCatalog = [
  {
    id: 1,
    articl: "Product Code UJIG0LO16031100",
    name: "Travel jacket in cashmere and cotton",
    price: "€ 1.379,51",
    img: "img/jacket-1.png",
    size: [44, 46, 48, 50, 52, 54, 56, 58, 60],
    color: ["Dark grey", "Black"],
    like: false,
    choice: [
      "img/card-choice-1.png",
      "img/card-choice-2.png",
      "img/card-choice-3.png",
      "img/card-choice-4.png",
      "img/card-choice-5.png",
    ],
  },
  {
    id: 2,
    articl: "Product Code GJIG0LO96031200",
    name: "Escorial Wool Blazer",
    price: "€ 1.244,27",
    img: "img/jacket-2.png",
    size: [44, 46, 48, 50, 52, 54, 56, 58, 60],
    color: ["Dark blue", "Black"],
    like: false,
  },
  {
    id: 3,
    name: "Sea Island Cotton Jacket",
    price: "€ 973,78",
    img: "img/jacket-3.png",
    like: false,
  },
  {
    id: 4,
    name: "Super Plume jacket made of flannel wool",
    price: "€ 865,58",
    img: "img/jacket-4.png",
    like: false,
  },
  {
    id: 5,
    name: "Super Plume jacket in cotton corduroy",
    price: "€ 1.803,27",
    img: "img/jacket-5.png",
    like: false,
  },
  {
    id: 6,
    name: "Virgilio jacket in silk and wool",
    price: "€ 4.147,54",
    img: "img/jacket-6.png",
    like: false,
  },
  {
    id: 7,
    name: "Natural wool travel jacket",
    price: "€ 3.786,88",
    img: "img/jacket-7.png",
    like: false,
  },
  {
    id: 8,
    name: "Ravello jacket in cashmere and silk",
    price: "€ 4.012,29",
    img: "img/jacket-8.png",
    like: false,
  },
  {
    id: 9,
    name: "Ravello jacket in sustainable cashmere",
    price: "€ 4.553,27",
    img: "img/jacket-9.png",
    like: false,
  },
];

export default dbCatalog;
